TARGET = "ATD"
ID = "delivery_trip_uuid"
DATE = "restaurant_offered_timestamp_local"
FEATURES = [
    "pickup_distance",
    "dropoff_distance",
    "order_hour",
    "order_dayofweek",
    "order_weekend",
    "order_time_of_day_encoded",
    "delivery_duration_minutes",
    "preparation_time_minutes",
    "delivery_hour",
    "total_distance_km",
    "distance_ratio",
    "long_delivery_flag",
    "courier_flow_encoded",
    "geo_archetype_encoded",
    "merchant_surface_encoded",
    "territory_encoded",
    "courier_flow_complexity_score",
    "is_peak_hour",
    "estimated_speed_kmh",
    "is_short_trip_long_time",
    "relative_prep_time",
    "is_high_traffic_suspected",
    "speed_below_threshold",
    "rain",
    "temp",
]
